# 是否打印进度
print-progress: false
# 保存方法
# 目前支持的保存方法: r2, local
save-method: r2
# 检查间隔,单位分钟
check-interval: 30
# 并发
concurrent: 200
# 下载大小 单位MB
download-size: 20
# 上传大小 单位MB
upload-size: 20
# 超时时间 单位毫秒
timeout: 5000
# 排除 正则
filter-regex: ""
# github token
github-token: ""
# gist id
github-gist-id: ""
# github api mirror
github-api-mirror: ""
#worker-url
worker-url: https://example.worker.dev
#worker-token
worker-token: 1234567890
# 订阅链接 clash/mihomo 格式
sub-urls:
  - https://example.com/sub.txt
ip-info:
  api-url: 
    - http://ifconfig.me
    - http://ip.sb
    - http://ifconfig.es
    - http://ipinfo.io/ip
    - http://ipecho.net/ip
    - http://ident.me
    - http://eth0.me
    - http://ipaddr.site
    - http://ipaddress.sh
    - http://l2.io/ip
    - http://tnx.nl/ip
    - http://wgetip.com
    - http://ip.tyk.nu
    - http://curlmyip.net
    - http://ipcalf.com
    - http://checkip.amazonaws.com
  ipdb-url: https://cdn.jsdelivr.net/npm/openipdb.ipdb@2025.1.4/openipdb.ipdb
  
